In [1]:
import pandas as pd
pd.set_option('max_column', None)
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
url = 'https://raw.githubusercontent.com/katenjoki/Telecom_Week1Challenge/main/OneDrive/Desktop/10Academy/Telecom_Week1Challenge/data/Week1_challenge_data_source(CSV).csv'
data = pd.read_csv(url)
data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [3]:
data.shape

(150001, 55)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

<h2>Task 1 : User Overview Analysis </h2>

<h3> Data Cleaning </h3>

In [5]:
data.columns = data.columns.str.replace(' ','_')
data.columns.to_list()

['Bearer_Id',
 'Start',
 'Start_ms',
 'End',
 'End_ms',
 'Dur._(ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last_Location_Name',
 'Avg_RTT_DL_(ms)',
 'Avg_RTT_UL_(ms)',
 'Avg_Bearer_TP_DL_(kbps)',
 'Avg_Bearer_TP_UL_(kbps)',
 'TCP_DL_Retrans._Vol_(Bytes)',
 'TCP_UL_Retrans._Vol_(Bytes)',
 'DL_TP_<_50_Kbps_(%)',
 '50_Kbps_<_DL_TP_<_250_Kbps_(%)',
 '250_Kbps_<_DL_TP_<_1_Mbps_(%)',
 'DL_TP_>_1_Mbps_(%)',
 'UL_TP_<_10_Kbps_(%)',
 '10_Kbps_<_UL_TP_<_50_Kbps_(%)',
 '50_Kbps_<_UL_TP_<_300_Kbps_(%)',
 'UL_TP_>_300_Kbps_(%)',
 'HTTP_DL_(Bytes)',
 'HTTP_UL_(Bytes)',
 'Activity_Duration_DL_(ms)',
 'Activity_Duration_UL_(ms)',
 'Dur._(ms).1',
 'Handset_Manufacturer',
 'Handset_Type',
 'Nb_of_sec_with_125000B_<_Vol_DL',
 'Nb_of_sec_with_1250B_<_Vol_UL_<_6250B',
 'Nb_of_sec_with_31250B_<_Vol_DL_<_125000B',
 'Nb_of_sec_with_37500B_<_Vol_UL',
 'Nb_of_sec_with_6250B_<_Vol_DL_<_31250B',
 'Nb_of_sec_with_6250B_<_Vol_UL_<_37500B',
 'Nb_of_sec_with_Vol_DL_<_6250B',
 'Nb_of_sec_with_Vol_UL_<_1250B',
 'Social_Media_DL_(Bytes)',
 'Social_Media_UL_(Bytes)',
 'Google_DL_(Bytes)',
 'Google_UL_(Bytes)',
 'Email_DL_(Bytes)',
 'Email_UL_(Bytes)',
 'Youtube_DL_(Bytes)',
 'Youtube_UL_(Bytes)',
 'Netflix_DL_(Bytes)',
 'Netflix_UL_(Bytes)',
 'Gaming_DL_(Bytes)',
 'Gaming_UL_(Bytes)',
 'Other_DL_(Bytes)',
 'Other_UL_(Bytes)',
 'Total_UL_(Bytes)',
 'Total_DL_(Bytes)']

**Checking for null values**

In [6]:
#Check if there are rows where all column values are null
check_null = data.columns.isnull().any()
check_null

False

In [7]:
#% of null values
def null_analysis(df):
    total_values = np.product(df.shape)
    total_null = (df.isnull().sum()).sum()
    proportion_null = (total_null / total_values)*100
    
    print("The Telcommunication dataset has ",proportion_null,"% null values.")

null_analysis(data)

The Telcommunication dataset has  12.501637867868759 % null values.

**Finding columns that have more than 30% of null values**

In [8]:
def null_per_column(df):
    dataset = df.isnull().sum()
    dataset = pd.DataFrame(dataset,columns=['null'])
    dataset['%null'] = (dataset['null']/df.shape[0])*100
    dataframe = dataset[dataset['%null']>=30]
    print(dataframe)    
    #print('\n List of columns with more than 30% null values:\n',dataframe.index.to_list())

null_per_column(data)

                                            null      %null
TCP_DL_Retrans._Vol_(Bytes)                88146  58.763608
TCP_UL_Retrans._Vol_(Bytes)                96649  64.432237
HTTP_DL_(Bytes)                            81474  54.315638
HTTP_UL_(Bytes)                            81810  54.539636
Nb_of_sec_with_125000B_<_Vol_DL            97538  65.024900
Nb_of_sec_with_1250B_<_Vol_UL_<_6250B      92894  61.928920
Nb_of_sec_with_31250B_<_Vol_DL_<_125000B   93586  62.390251
Nb_of_sec_with_37500B_<_Vol_UL            130254  86.835421
Nb_of_sec_with_6250B_<_Vol_DL_<_31250B     88317  58.877607
Nb_of_sec_with_6250B_<_Vol_UL_<_37500B    111843  74.561503

In [9]:
#Dropping columns with more than 30% null values
data=data.drop(['TCP_DL_Retrans._Vol_(Bytes)', 'TCP_UL_Retrans._Vol_(Bytes)', 'HTTP_DL_(Bytes)', 'HTTP_UL_(Bytes)', 'Nb_of_sec_with_125000B_<_Vol_DL', 'Nb_of_sec_with_1250B_<_Vol_UL_<_6250B', 'Nb_of_sec_with_31250B_<_Vol_DL_<_125000B', 'Nb_of_sec_with_37500B_<_Vol_UL', 'Nb_of_sec_with_6250B_<_Vol_DL_<_31250B', 'Nb_of_sec_with_6250B_<_Vol_UL_<_37500B'],axis=1)
data.shape

(150001, 45)

In [10]:
data.isnull().sum()

Bearer_Id                           991
Start                                 1
Start_ms                              1
End                                   1
End_ms                                1
Dur._(ms)                             1
IMSI                                570
MSISDN/Number                      1066
IMEI                                572
Last_Location_Name                 1153
Avg_RTT_DL_(ms)                   27829
Avg_RTT_UL_(ms)                   27812
Avg_Bearer_TP_DL_(kbps)               1
Avg_Bearer_TP_UL_(kbps)               1
DL_TP_<_50_Kbps_(%)                 754
50_Kbps_<_DL_TP_<_250_Kbps_(%)      754
250_Kbps_<_DL_TP_<_1_Mbps_(%)       754
DL_TP_>_1_Mbps_(%)                  754
UL_TP_<_10_Kbps_(%)                 792
10_Kbps_<_UL_TP_<_50_Kbps_(%)       792
50_Kbps_<_UL_TP_<_300_Kbps_(%)      792
UL_TP_>_300_Kbps_(%)                792
Activity_Duration_DL_(ms)             1
Activity_Duration_UL_(ms)             1
Dur._(ms).1                           1
Handset_Manufacturer                572
Handset_Type                        572
Nb_of_sec_with_Vol_DL_<_6250B       755
Nb_of_sec_with_Vol_UL_<_1250B       793
Social_Media_DL_(Bytes)               0
Social_Media_UL_(Bytes)               0
Google_DL_(Bytes)                     0
Google_UL_(Bytes)                     0
Email_DL_(Bytes)                      0
Email_UL_(Bytes)                      0
Youtube_DL_(Bytes)                    0
Youtube_UL_(Bytes)                    0
Netflix_DL_(Bytes)                    0
Netflix_UL_(Bytes)                    0
Gaming_DL_(Bytes)                     0
Gaming_UL_(Bytes)                     0
Other_DL_(Bytes)                      0
Other_UL_(Bytes)                      0
Total_UL_(Bytes)                      1
Total_DL_(Bytes)                      1
dtype: int64

* Column Bearer Id has 991 values, we drop these rows as the Bearer Id should be a unique identifier

In [11]:
data = data[data['Bearer_Id'].notna()]
data.isnull().sum()

Bearer_Id                             0
Start                                 0
Start_ms                              0
End                                   0
End_ms                                0
Dur._(ms)                             0
IMSI                                  9
MSISDN/Number                       504
IMEI                                 11
Last_Location_Name                  162
Avg_RTT_DL_(ms)                   27685
Avg_RTT_UL_(ms)                   27666
Avg_Bearer_TP_DL_(kbps)               0
Avg_Bearer_TP_UL_(kbps)               0
DL_TP_<_50_Kbps_(%)                 716
50_Kbps_<_DL_TP_<_250_Kbps_(%)      716
250_Kbps_<_DL_TP_<_1_Mbps_(%)       716
DL_TP_>_1_Mbps_(%)                  716
UL_TP_<_10_Kbps_(%)                 770
10_Kbps_<_UL_TP_<_50_Kbps_(%)       770
50_Kbps_<_UL_TP_<_300_Kbps_(%)      770
UL_TP_>_300_Kbps_(%)                770
Activity_Duration_DL_(ms)             0
Activity_Duration_UL_(ms)             0
Dur._(ms).1                           0
Handset_Manufacturer                 11
Handset_Type                         11
Nb_of_sec_with_Vol_DL_<_6250B       717
Nb_of_sec_with_Vol_UL_<_1250B       771
Social_Media_DL_(Bytes)               0
Social_Media_UL_(Bytes)               0
Google_DL_(Bytes)                     0
Google_UL_(Bytes)                     0
Email_DL_(Bytes)                      0
Email_UL_(Bytes)                      0
Youtube_DL_(Bytes)                    0
Youtube_UL_(Bytes)                    0
Netflix_DL_(Bytes)                    0
Netflix_UL_(Bytes)                    0
Gaming_DL_(Bytes)                     0
Gaming_UL_(Bytes)                     0
Other_DL_(Bytes)                      0
Other_UL_(Bytes)                      0
Total_UL_(Bytes)                      0
Total_DL_(Bytes)                      0
dtype: int64

In [12]:
#replace null values for object types with mode
def null_objects(df,column):
    df[column] = df[column].fillna(df[column].mode()[0])
    return df[column]

data['Last_Location_Name'] = null_objects(data,'Last_Location_Name')
data['Handset_Manufacturer'] = null_objects(data,'Handset_Manufacturer')
data['Handset_Type']= null_objects(data,'Handset_Type')

In [13]:
#list of columns with null values,
def null_values(df):
    dataframe=df.isnull().sum()
    dataframe=pd.DataFrame(dataframe,columns=['null'])
    dataframe=dataframe[dataframe['null']>0]
    print(dataframe.index.to_list())

null_values(data)

['IMSI', 'MSISDN/Number', 'IMEI', 'Avg_RTT_DL_(ms)', 'Avg_RTT_UL_(ms)', 'DL_TP_<_50_Kbps_(%)', '50_Kbps_<_DL_TP_<_250_Kbps_(%)', '250_Kbps_<_DL_TP_<_1_Mbps_(%)', 'DL_TP_>_1_Mbps_(%)', 'UL_TP_<_10_Kbps_(%)', '10_Kbps_<_UL_TP_<_50_Kbps_(%)', '50_Kbps_<_UL_TP_<_300_Kbps_(%)', 'UL_TP_>_300_Kbps_(%)', 'Nb_of_sec_with_Vol_DL_<_6250B', 'Nb_of_sec_with_Vol_UL_<_1250B']

In [14]:
#check skewness
data_test=data[['IMSI', 'MSISDN/Number', 'IMEI', 'Avg_RTT_DL_(ms)', 'Avg_RTT_UL_(ms)', 'DL_TP_<_50_Kbps_(%)', '50_Kbps_<_DL_TP_<_250_Kbps_(%)', '250_Kbps_<_DL_TP_<_1_Mbps_(%)', 'DL_TP_>_1_Mbps_(%)', 'UL_TP_<_10_Kbps_(%)', '10_Kbps_<_UL_TP_<_50_Kbps_(%)', '50_Kbps_<_UL_TP_<_300_Kbps_(%)', 'UL_TP_>_300_Kbps_(%)', 'Nb_of_sec_with_Vol_DL_<_6250B', 'Nb_of_sec_with_Vol_UL_<_1250B']]
data_test.skew()

IMSI                               40.987487
MSISDN/Number                     331.677128
IMEI                                1.070670
Avg_RTT_DL_(ms)                    66.756066
Avg_RTT_UL_(ms)                    28.499279
DL_TP_<_50_Kbps_(%)                -2.298563
50_Kbps_<_DL_TP_<_250_Kbps_(%)      3.273358
250_Kbps_<_DL_TP_<_1_Mbps_(%)       4.571437
DL_TP_>_1_Mbps_(%)                  5.361127
UL_TP_<_10_Kbps_(%)                -8.985914
10_Kbps_<_UL_TP_<_50_Kbps_(%)      10.946940
50_Kbps_<_UL_TP_<_300_Kbps_(%)     21.833582
UL_TP_>_300_Kbps_(%)               36.151871
Nb_of_sec_with_Vol_DL_<_6250B       9.024910
Nb_of_sec_with_Vol_UL_<_1250B       7.482728
dtype: float64

In [15]:
#since data is skewed we replace the null values with the median
column_names = ['IMSI', 'MSISDN/Number', 'IMEI', 'Avg_RTT_DL_(ms)', 'Avg_RTT_UL_(ms)', 'DL_TP_<_50_Kbps_(%)', '50_Kbps_<_DL_TP_<_250_Kbps_(%)', '250_Kbps_<_DL_TP_<_1_Mbps_(%)', 'DL_TP_>_1_Mbps_(%)', 'UL_TP_<_10_Kbps_(%)', '10_Kbps_<_UL_TP_<_50_Kbps_(%)', '50_Kbps_<_UL_TP_<_300_Kbps_(%)', 'UL_TP_>_300_Kbps_(%)', 'Nb_of_sec_with_Vol_DL_<_6250B', 'Nb_of_sec_with_Vol_UL_<_1250B']

for i in column_names:
    data[i]=data[i].fillna(data[i].mean())

(data.isnull().sum()).sum()

0